apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
        version: latest
    spec:
      containers:
      - name: demo-app
        image: nginx
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 80
        env:
        - name: VERSION
          value: latest
